version: "3.7"

services:
  db:
    container_name: db-cadastro-pessoas
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=cadastro_pessoas
