version: "3.9"
services:
  db-cadastro-pessoas:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cadastro_pessoas
    ports:
      - '5432:5432'
    volumes:
      - db-cadastro-pessoas:/var/lib/postgresql/data

  app-cadastro-pessoas:
    build:
      context: ./
    environment:
      DB_DATABASE: cadastro_pessoas
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db-cadastro-pessoas
    depends_on:
      - db-cadastro-pessoas
    ports:
      - '3000:3000'

volumes:
  db-cadastro-pessoas:
