# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        postgres-version: [14]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Start PostgreSQL ${{ matrix.postgres-version }}
        uses: ankane/setup-postgres@v1
        env:
            DB_USER: 'postgres'
            DB_PASSWORD: 'postgres'
            DB_HOST: 'localhost'
            DB_PORT: '5432'
            DB_VERSION: ${{ matrix.postgres-version }}
            DB_DATABASE: 'cadastro_pessoas'
        with:
          version: ${{ matrix.postgres-version }}
          port: 5432
          database: cadastro_pessoas
          user: postgres
          password: postgres
          host: postgres
          schema: public
          cleanup: true

      - name: Install dependencies
        run: npm ci --frozen-lockfile

      - name: Build
        run: npm run build --if-present

      - name: Run tests
        run: npm test
