# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: node:latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: cadastro_pessoas
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Install PostgreSQL client
          # ...
          - name: Setup database
          run: psql -h postgres -U postgres_user -c 'CREATE DATABASE "cadastro_pessoas";'
          env:
            POSTGRES_PASSWORD: postgres
      - name: Install dependencies
        run: npm ci --frozen-lockfile
      - name: Build
        run: npm run build --if-present
      - name: Run tests
        run: npm test
